CREATE TABLE ASIGNATURA(
    CODASIG NUMBER (3),
    NOMBRE VARCHAR2 (30),
    NUMHORAS NUMBER (3),
    CONSTRAINT pk_asignatura PRIMARY KEY (CODASIG)
);

CREATE TABLE ALUMNO(
    DNI VARCHAR (9),
    NOMBRE VARCHAR2 (30),
    APELLIDO1 VARCHAR2 (50),
    APELLIDO1 VARCHAR2 (50) NOT NULL,
    CONSTRAINT pk_alumno PRIMARY KEY (DNI)
);

--TABLA RELACIONES
CREATE TABLE INSCRIPCION(
    CODASIG NUMBER (3),
    DNI VARCHAR (9),
    CALIFICACION NUMBER (2),
    CONSTRAINT pk_inscripcion PRIMARY KEY (CODASIG, DNI),
    CONSTRAINT fk_asignatura FOREIGN KEY(CODASIG) REFERENCES ASIGNATURA(CODASIG),
    CONSTRAINT fk_alumno FOREIGN KEY(DNI) REFERENCES ALUMNO(DNI)
)